package net.lashua.zonedit.io

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import net.lashua.zonedit.model.ExitDirection
import net.lashua.zonedit.model.Position
import net.lashua.zonedit.model.Room
import net.lashua.zonedit.model.Zone
import net.peanuuutz.tomlkt.Toml
import org.slf4j.LoggerFactory
import java.io.File

@Serializable
data class ZoneFile(
    val name: String,
    val id: String,
    @SerialName("node_width.f")
    val nodeWidth: Float = 100f,
    @SerialName("node_height.f")
    val nodeHeight: Float = 60f,
    @SerialName("grid_size.f")
    val gridSize: Float = 20f,
    @SerialName("snap_to_grid")
    val snapToGrid: Boolean = true,
    val rooms: List<SerializableRoom> = emptyList()
)

@Serializable
data class SerializableRoom(
    val id: String,
    val name: String,
    val description: String,
    val position: SerializablePosition,
    val exits: Map<String, String> = emptyMap(),
    @SerialName("exit_corners")
    val exitCorners: Map<String, String> = emptyMap(),
    val flags: List<String> = emptyList(),
    val metadata: Map<String, String> = emptyMap()
)

@Serializable
data class SerializablePosition(
    val x: Float,
    val y: Float
)

object ZoneSerializer {
    private val log = LoggerFactory.getLogger(ZoneSerializer::class.java)
    private val toml = Toml { 
        ignoreUnknownKeys = true
    }

    fun saveZone(zone: Zone, file: File) {
        log.debug("Preparing to save zone '${zone.name}' to ${file.absolutePath}")
        val zoneFile = ZoneFile(
            name = zone.name,
            id = zone.id,
            nodeWidth = zone.nodeWidthDp,
            nodeHeight = zone.nodeHeightDp,
            gridSize = zone.gridSizeDp,
            snapToGrid = zone.snapToGrid,
            rooms = zone.rooms.map { room ->
                SerializableRoom(
                    id = room.id,
                    name = room.name,
                    description = formatMultilineString(room.description),
                    position = SerializablePosition(room.position.x, room.position.y),
                    exits = room.exits.entries.associate { (direction, destId) -> 
                        direction.name.lowercase() to destId 
                    },
                    flags = room.flags
                )
            }
        )
        
        log.debug("Serialized zone contains ${zoneFile.rooms.size} rooms")
        
        val header = """# Zone file for ${zone.name}
# Generated by ZoneEdit
# Last modified: ${java.time.LocalDateTime.now()}

"""
        
        val tomlContent = toml.encodeToString(ZoneFile.serializer(), zoneFile)
        log.debug("Generated TOML content (first 100 chars): ${tomlContent.take(100)}...")
        
        try {
            file.writeText(header + tomlContent)
            log.info("Successfully wrote ${file.length()} bytes to ${file.absolutePath}")
        } catch (e: Exception) {
            log.error("Failed to write file", e)
            throw e
        }
    }

    private fun formatMultilineString(text: String): String {
        return if (text.contains('\n')) {
            text.trim()
        } else {
            text
        }
    }

    fun loadZone(file: File): Zone {
        log.debug("Starting to load zone from file: ${file.absolutePath}")
        val content = file.readText()
        
        try {
            val contentWithoutComments = content.lines()
                .filterNot { it.trimStart().startsWith('#') }
                .joinToString("\n")
            
            log.debug("Attempting to parse TOML content")
            val zoneFile = toml.decodeFromString(ZoneFile.serializer(), contentWithoutComments)
            log.debug("Successfully parsed zone file with ${zoneFile.rooms.size} rooms")
            
            return Zone(
                id = zoneFile.id,
                name = zoneFile.name,
                nodeWidthDp = zoneFile.nodeWidth,
                nodeHeightDp = zoneFile.nodeHeight,
                gridSizeDp = zoneFile.gridSize,
                snapToGrid = zoneFile.snapToGrid,
                rooms = zoneFile.rooms.map { room ->
                    Room(
                        id = room.id,
                        name = room.name,
                        description = room.description,
                        position = Position(room.position.x, room.position.y),
                        exits = room.exits.entries.associate { (direction, destId) -> 
                            ExitDirection.valueOf(direction.uppercase()) to destId 
                        },
                        exitCorners = room.exitCorners.entries.associate { (direction, corner) ->
                            ExitDirection.valueOf(direction.uppercase()) to corner
                        },
                        flags = room.flags
                    )
                }
            )
        } catch (e: Exception) {
            log.error("Failed to parse zone file: ${e.message}", e)
            throw e
        }
    }
}